name: Build and Deploy
on: 
  workflow_dispatch
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: |
          docker build -t myapp:latest .
      - name: Sign in to Azure
        uses: azure/login@v2
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: Push to ACR
        run: |
          az acr login -n sslablabacrdg
          docker tag myapp:latest sslablabacrdg.azurecr.io/myapp:latest
          docker push sslablabacrdg.azurecr.io/myapp:latest
      - name: Deploy to WebApp
        run: |
          az webapp config container set \
          -g ss-lab-rg-dg \
          -n sslab-webappdg \
          --container-image-name sslablabacrdg.azurecr.io/myapp:latest \
          --container-registry-url https://sslablabacrdg.azurecr.io \
          --container-registry-user ${{secrets.ACR_USER}} \
          --container-registry-password ${{secrets.ACR_PWD}}

